channels:
- conda-forge
- bioconda
dependencies:
- fastqc=0.11.9
- sra-tools=2.7.0
 # Specify python version (not required but can help with downstream conflicts)
- python=3.7.6

# The workflow manager
- snakemake-minimal=5.10.0

# For visualizing workflows
- graphviz=2.42.3
- xorg-libxrender
- xorg-libxpm

# For downloading files
- wget=1.20.1
